name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
        poetry-version: ["1.7.1"]
        mint-only-deprecated: ["false", "true"]
        mint-database: ["./test_data/test_mint", "postgres://cashu:cashu@localhost:5432/cashu"]
        backend-wallet-class: ["FakeWallet"]
    uses: ./.github/workflows/tests.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      poetry-version: ${{ matrix.poetry-version }}
      mint-only-deprecated: ${{ matrix.mint-only-deprecated }}
      mint-database: ${{ matrix.mint-database }}
  regtest:
    uses: ./.github/workflows/regtest.yml
    strategy:
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.7.1"]
        backend-wallet-class:
          ["LndRestWallet", "CLNRestWallet", "CoreLightningRestWallet", "LNbitsWallet"]
        mint-database: ["./test_data/test_mint", "postgres://cashu:cashu@localhost:5432/cashu"]
        # mint-database: ["./test_data/test_mint"]
    with:
      python-version: ${{ matrix.python-version }}
      backend-wallet-class: ${{ matrix.backend-wallet-class }}
      mint-database: ${{ matrix.mint-database }}
