name: tests

on:
  workflow_call:
    inputs:
      python-version:
        default: "3.10.4"
        type: string
      poetry-version:
        default: "1.5.1"
        type: string
      os:
        default: "ubuntu-latest"
        type: string

jobs:
  poetry:
    runs-on: ${{ inputs.os }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: cashu
          POSTGRES_PASSWORD: cashu
          POSTGRES_DB: cashu
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
      - uses: ./.github/actions/prepare
        with:
          python-version: ${{ inputs.python-version }}
          poetry-version: ${{ inputs.poetry-version }}
      - name: Run tests
        env:
          WALLET_NAME: test_wallet
          MINT_HOST: localhost
          MINT_PORT: 3337
          MINT_DATABASE: ${{ inputs.db-url }}
          TOR: false
        run: |
          make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
